### ISSUE TITLE
Suggestion: Use the official SFML.Net Nuget and Change to .Net Core 2.2+

### ISSUE THREAD

**Issue by drako0812** [texus/TGUI.Net#4]
Once again, just a suggestion. Also, I realize this would be a quite big change to your workflow.

**Comment by texus** [comment]
Changing the workflow isn't the problem, I just don't thing that using the official SFML.Net nuget in TGUI.Net is possible at all.
The TGUI library that TGUI.Net uses has to be compiled with the identical SFML library that was used to compile CSFML used by SFML.Net. The only way that I know to ensure compatibility between all dependencies is to build them all together and ship them with TGUI.Net.

There is no need for a library to update to a newer .Net Core version as far as I know. Programs should use a version as new as possible to have the latest features, but libraries should use a version as old as possible to allow more people to use it. You should still be able to use TGUI.Net without issues when you use .Net Core 2.2+ in your project. Increasing the version of TGUI.Net has no benefit that I know of and would only limit who can use it.

**Comment by drako0812** [comment]
Fair enough. I just thought I'd bring your attention to it, if you weren't aware.

**Comment by texus** [comment]
Thanks for the effort anyway. At least it is documented now why I don't use it so people will hopefully find this issue is they also wonder why I'm not using the nuget or the latest .net core version.
