### ISSUE TITLE
The version is too old

### ISSUE THREAD

**Issue by XiangQinxi** [texus/TGUI.Net#5]
No AutoSize

**Comment by texus** [comment]
The TGUI.Net binding is no longer being developed (as mentioned in the top of the readme), it only contains functionality that existed in TGUI 0.8

While I would like to bring the binding back, there are too many complication to get it working properly which would take too much effort.

**Comment by texus** [comment]
TGUI.Net has been revived and updated to the latest TGUI version.

While it still needs improvements and a lot of testing, a new `1.6.0.1-alpha` version is available on [NuGet](https://www.nuget.org/packages/TGUI.Net).
